/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function Model3(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/untitled.glb");
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group
          name="Sketchfab_model"
          position={[2.919, 2.772, 1.511]}
          rotation={[-Math.PI, 0, -Math.PI / 2]}
          scale={-0.008}
        >
          <group name="1_cubefbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group
                  name="Cube000"
                  position={[0, 0, -0.459]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                >
                  <mesh
                    name="Cube000_Cube_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube000_Cube_0.geometry}
                    material={materials.Cube}
                  />
                </group>
                <group
                  name="Cube001"
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                >
                  <mesh
                    name="Cube001_Cube_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube001_Cube_0.geometry}
                    material={materials.Cube}
                  />
                </group>
                <group name="Cube007" rotation={[0, 1.571, 0]} scale={100}>
                  <mesh
                    name="Cube007_Cube_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube007_Cube_0.geometry}
                    material={materials.Cube}
                  />
                </group>
                <group
                  name="Cube008"
                  rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                  scale={100}
                >
                  <mesh
                    name="Cube008_Cube_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube008_Cube_0.geometry}
                    material={materials.Cube}
                  />
                </group>
                <group name="Cube009" rotation={[3.138, 0, 0]} scale={100}>
                  <mesh
                    name="Cube009_Cube_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube009_Cube_0.geometry}
                    material={materials.Cube}
                  />
                </group>
                <group name="Cube010" rotation={[0, 1.571, 0]} scale={100}>
                  <mesh
                    name="Cube010_Cube_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube010_Cube_0.geometry}
                    material={materials.Cube}
                  />
                </group>
                <group
                  name="Cube011"
                  rotation={[-Math.PI / 2, 0, Math.PI / 2]}
                  scale={100}
                >
                  <mesh
                    name="Cube011_Cube_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube011_Cube_0.geometry}
                    material={materials.Cube}
                  />
                </group>
                <group
                  name="Cube012"
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                >
                  <mesh
                    name="Cube012_Cube_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube012_Cube_0.geometry}
                    material={materials.Cube}
                  />
                </group>
                <group
                  name="Cube014"
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                >
                  <mesh
                    name="Cube014_Cube_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube014_Cube_0.geometry}
                    material={materials.Cube}
                  />
                </group>
                <group
                  name="Cube015"
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                >
                  <mesh
                    name="Cube015_Cube_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube015_Cube_0.geometry}
                    material={materials.Cube}
                  />
                </group>
                <group
                  name="Cube016"
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                >
                  <mesh
                    name="Cube016_Cube_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube016_Cube_0.geometry}
                    material={materials.Cube}
                  />
                </group>
                <group
                  name="Cube017"
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                >
                  <mesh
                    name="Cube017_Cube_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube017_Cube_0.geometry}
                    material={materials.Cube}
                  />
                </group>
                <group
                  name="Cube018"
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                >
                  <mesh
                    name="Cube018_Cube_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube018_Cube_0.geometry}
                    material={materials.Cube}
                  />
                </group>
                <group
                  name="Cube019"
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                >
                  <mesh
                    name="Cube019_Cube_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube019_Cube_0.geometry}
                    material={materials.Cube}
                  />
                </group>
                <group
                  name="Cube020"
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                >
                  <mesh
                    name="Cube020_Cube_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube020_Cube_0.geometry}
                    material={materials.Cube}
                  />
                </group>
                <group name="Cube021" rotation={[0, 1.571, 0]} scale={100}>
                  <mesh
                    name="Cube021_Cube_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube021_Cube_0.geometry}
                    material={materials.Cube}
                  />
                </group>
                <group name="Cube022" rotation={[0, 1.571, 0]} scale={100}>
                  <mesh
                    name="Cube022_Cube_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube022_Cube_0.geometry}
                    material={materials.Cube}
                  />
                </group>
                <group name="Cube023" rotation={[0, 1.571, 0]} scale={100}>
                  <mesh
                    name="Cube023_Cube_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube023_Cube_0.geometry}
                    material={materials.Cube}
                  />
                </group>
                <group name="Cube024" rotation={[0, 1.571, 0]} scale={100}>
                  <mesh
                    name="Cube024_Cube_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube024_Cube_0.geometry}
                    material={materials.Cube}
                  />
                </group>
                <group
                  name="Cube025"
                  rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                  scale={100}
                >
                  <mesh
                    name="Cube025_Cube_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube025_Cube_0.geometry}
                    material={materials.Cube}
                  />
                </group>
                <group
                  name="Cube026"
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                >
                  <mesh
                    name="Cube026_Cube_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube026_Cube_0.geometry}
                    material={materials.Cube}
                  />
                </group>
                <group
                  name="Cube027"
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                >
                  <mesh
                    name="Cube027_Cube_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube027_Cube_0.geometry}
                    material={materials.Cube}
                  />
                </group>
                <group
                  name="Cube029"
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                >
                  <mesh
                    name="Cube029_Cube_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube029_Cube_0.geometry}
                    material={materials.Cube}
                  />
                </group>
                <group
                  name="Cube030"
                  rotation={[-Math.PI / 2, 0, Math.PI / 2]}
                  scale={100}
                >
                  <mesh
                    name="Cube030_Cube_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube030_Cube_0.geometry}
                    material={materials.Cube}
                  />
                </group>
                <group
                  name="Cube031"
                  rotation={[-Math.PI / 2, 0, Math.PI / 2]}
                  scale={100}
                >
                  <mesh
                    name="Cube031_Cube_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube031_Cube_0.geometry}
                    material={materials.Cube}
                  />
                </group>
                <group
                  name="Cube032"
                  rotation={[-Math.PI / 2, 0, Math.PI / 2]}
                  scale={100}
                >
                  <mesh
                    name="Cube032_Cube_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube032_Cube_0.geometry}
                    material={materials.Cube}
                  />
                </group>
                <group
                  name="Cube033"
                  rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                  scale={100}
                >
                  <mesh
                    name="Cube033_Red_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube033_Red_0.geometry}
                    material={materials.material}
                  />
                </group>
                <group
                  name="Cube034"
                  rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                  scale={100}
                >
                  <mesh
                    name="Cube034_Red_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube034_Red_0.geometry}
                    material={materials.material}
                  />
                </group>
                <group
                  name="Cube035"
                  rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                  scale={100}
                >
                  <mesh
                    name="Cube035_Red_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube035_Red_0.geometry}
                    material={materials.material}
                  />
                </group>
                <group
                  name="Cube036"
                  rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                  scale={100}
                >
                  <mesh
                    name="Cube036_Red_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube036_Red_0.geometry}
                    material={materials.material}
                  />
                </group>
                <group name="Cube037" rotation={[0, 1.571, 0]} scale={100}>
                  <mesh
                    name="Cube037_Red_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube037_Red_0.geometry}
                    material={materials.material}
                  />
                </group>
                <group
                  name="Cube038"
                  rotation={[Math.PI / 2, 0, -Math.PI]}
                  scale={100}
                >
                  <mesh
                    name="Cube038_Red_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube038_Red_0.geometry}
                    material={materials.material}
                  />
                </group>
                <group
                  name="Cube039"
                  rotation={[Math.PI / 2, 0, Math.PI]}
                  scale={100}
                >
                  <mesh
                    name="Cube039_Green_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube039_Green_0.geometry}
                    material={materials.Green}
                  />
                </group>
                <group name="Cube040" rotation={[0, 1.571, 0]} scale={100}>
                  <mesh
                    name="Cube040_Red_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube040_Red_0.geometry}
                    material={materials.material}
                  />
                </group>
                <group
                  name="Cube041"
                  rotation={[-Math.PI / 2, 1.571, 0]}
                  scale={100}
                >
                  <mesh
                    name="Cube041_Red_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube041_Red_0.geometry}
                    material={materials.material}
                  />
                </group>
                <group
                  name="Cube042"
                  rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                  scale={100}
                >
                  <mesh
                    name="Cube042_Green_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube042_Green_0.geometry}
                    material={materials.Green}
                  />
                </group>
                <group
                  name="Cube043"
                  rotation={[1.571, 0, Math.PI]}
                  scale={100}
                >
                  <mesh
                    name="Cube043_Green_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube043_Green_0.geometry}
                    material={materials.Green}
                  />
                </group>
                <group
                  name="Cube044"
                  rotation={[1.571, 0, Math.PI]}
                  scale={100}
                >
                  <mesh
                    name="Cube044_Green_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube044_Green_0.geometry}
                    material={materials.Green}
                  />
                </group>
                <group
                  name="Cube045"
                  rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
                  scale={100}
                >
                  <mesh
                    name="Cube045_Green_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube045_Green_0.geometry}
                    material={materials.Green}
                  />
                </group>
                <group
                  name="Cube046"
                  rotation={[1.571, 0, Math.PI]}
                  scale={100}
                >
                  <mesh
                    name="Cube046_Green_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube046_Green_0.geometry}
                    material={materials.Green}
                  />
                </group>
                <group
                  name="Cube047"
                  rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                  scale={100}
                >
                  <mesh
                    name="Cube047_Green_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube047_Green_0.geometry}
                    material={materials.Green}
                  />
                </group>
                <group
                  name="Cube048"
                  rotation={[Math.PI / 2, 0, Math.PI]}
                  scale={100}
                >
                  <mesh
                    name="Cube048_Green_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube048_Green_0.geometry}
                    material={materials.Green}
                  />
                </group>
                <group
                  name="Cube049"
                  rotation={[Math.PI / 2, -0.004, -Math.PI]}
                  scale={100}
                >
                  <mesh
                    name="Cube049_Green_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube049_Green_0.geometry}
                    material={materials.Green}
                  />
                </group>
                <group
                  name="Cube050"
                  rotation={[-Math.PI / 2, -1.571, 0]}
                  scale={100}
                >
                  <mesh
                    name="Cube050_Orange_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube050_Orange_0.geometry}
                    material={materials.Orange}
                  />
                </group>
                <group
                  name="Cube051"
                  rotation={[-Math.PI / 2, -1.571, 0]}
                  scale={100}
                >
                  <mesh
                    name="Cube051_Orange_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube051_Orange_0.geometry}
                    material={materials.Orange}
                  />
                </group>
                <group
                  name="Cube052"
                  rotation={[-1.571, -1.567, 1.571]}
                  scale={100}
                >
                  <mesh
                    name="Cube052_Orange_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube052_Orange_0.geometry}
                    material={materials.Orange}
                  />
                </group>
                <group
                  name="Cube053"
                  rotation={[-Math.PI / 2, -1.571, 0]}
                  scale={100}
                >
                  <mesh
                    name="Cube053_Orange_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube053_Orange_0.geometry}
                    material={materials.Orange}
                  />
                </group>
                <group name="Cube054" rotation={[3.138, 0, 0]} scale={100}>
                  <mesh
                    name="Cube054_Orange_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube054_Orange_0.geometry}
                    material={materials.Orange}
                  />
                </group>
                <group
                  name="Cube055"
                  rotation={[-Math.PI / 2, -1.571, 0]}
                  scale={100}
                >
                  <mesh
                    name="Cube055_Orange_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube055_Orange_0.geometry}
                    material={materials.Orange}
                  />
                </group>
                <group
                  name="Cube056"
                  rotation={[-Math.PI / 2, -1.571, 0]}
                  scale={100}
                >
                  <mesh
                    name="Cube056_Orange_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube056_Orange_0.geometry}
                    material={materials.Orange}
                  />
                </group>
                <group
                  name="Cube057"
                  rotation={[-1.571, -1.567, 1.571]}
                  scale={100}
                >
                  <mesh
                    name="Cube057_Orange_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube057_Orange_0.geometry}
                    material={materials.Orange}
                  />
                </group>
                <group
                  name="Cube058"
                  rotation={[-Math.PI / 2, -1.571, 0]}
                  scale={100}
                >
                  <mesh
                    name="Cube058_Orange_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube058_Orange_0.geometry}
                    material={materials.Orange}
                  />
                </group>
                <group
                  name="Cube059"
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                >
                  <mesh
                    name="Cube059_Blue_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube059_Blue_0.geometry}
                    material={materials.Blue}
                  />
                </group>
                <group
                  name="Cube060"
                  rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                  scale={100}
                >
                  <mesh
                    name="Cube060_Red_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube060_Red_0.geometry}
                    material={materials.material}
                  />
                </group>
                <group
                  name="Cube061"
                  rotation={[-Math.PI / 2, 0, Math.PI / 2]}
                  scale={100}
                >
                  <mesh
                    name="Cube061_Blue_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube061_Blue_0.geometry}
                    material={materials.Blue}
                  />
                </group>
                <group
                  name="Cube062"
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                >
                  <mesh
                    name="Cube062_Blue_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube062_Blue_0.geometry}
                    material={materials.Blue}
                  />
                </group>
                <group
                  name="Cube063"
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                >
                  <mesh
                    name="Cube063_Blue_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube063_Blue_0.geometry}
                    material={materials.Blue}
                  />
                </group>
                <group
                  name="Cube064"
                  rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                  scale={100}
                >
                  <mesh
                    name="Cube064_Blue_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube064_Blue_0.geometry}
                    material={materials.Blue}
                  />
                </group>
                <group
                  name="Cube065"
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                >
                  <mesh
                    name="Cube065_Blue_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube065_Blue_0.geometry}
                    material={materials.Blue}
                  />
                </group>
                <group
                  name="Cube066"
                  rotation={[-Math.PI / 2, 0, Math.PI / 2]}
                  scale={100}
                >
                  <mesh
                    name="Cube066_Blue_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube066_Blue_0.geometry}
                    material={materials.Blue}
                  />
                </group>
                <group
                  name="Cube067"
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                >
                  <mesh
                    name="Cube067_Blue_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube067_Blue_0.geometry}
                    material={materials.Blue}
                  />
                </group>
                <group
                  name="Cube068"
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                >
                  <mesh
                    name="Cube068_Blue_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube068_Blue_0.geometry}
                    material={materials.Blue}
                  />
                </group>
                <group name="Cube069" scale={100}>
                  <mesh
                    name="Cube069_White_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube069_White_0.geometry}
                    material={materials.White}
                  />
                </group>
                <group name="Cube070" scale={100}>
                  <mesh
                    name="Cube070_White_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube070_White_0.geometry}
                    material={materials.White}
                  />
                </group>
                <group name="Cube071" rotation={[0, 0, 1.571]} scale={100}>
                  <mesh
                    name="Cube071_White_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube071_White_0.geometry}
                    material={materials.White}
                  />
                </group>
                <group name="Cube072" scale={100}>
                  <mesh
                    name="Cube072_White_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube072_White_0.geometry}
                    material={materials.White}
                  />
                </group>
                <group name="Cube073" rotation={[0, 1.571, 0]} scale={100}>
                  <mesh
                    name="Cube073_White_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube073_White_0.geometry}
                    material={materials.White}
                  />
                </group>
                <group name="Cube074" scale={100}>
                  <mesh
                    name="Cube074_White_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube074_White_0.geometry}
                    material={materials.White}
                  />
                </group>
                <group name="Cube075" scale={100}>
                  <mesh
                    name="Cube075_White_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube075_White_0.geometry}
                    material={materials.White}
                  />
                </group>
                <group name="Cube076" rotation={[0, 0, 1.571]} scale={100}>
                  <mesh
                    name="Cube076_White_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube076_White_0.geometry}
                    material={materials.White}
                  />
                </group>
                <group name="Cube077" scale={100}>
                  <mesh
                    name="Cube077_White_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube077_White_0.geometry}
                    material={materials.White}
                  />
                </group>
                <group
                  name="Cube078"
                  rotation={[Math.PI, -0.004, Math.PI]}
                  scale={100}
                >
                  <mesh
                    name="Cube078_Yellow_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube078_Yellow_0.geometry}
                    material={materials.Yellow}
                  />
                </group>
                <group
                  name="Cube079"
                  rotation={[-Math.PI, -0.004, -1.571]}
                  scale={100}
                >
                  <mesh
                    name="Cube079_Yellow_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube079_Yellow_0.geometry}
                    material={materials.Yellow}
                  />
                </group>
                <group
                  name="Cube080"
                  rotation={[Math.PI, -0.004, Math.PI]}
                  scale={100}
                >
                  <mesh
                    name="Cube080_Yellow_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube080_Yellow_0.geometry}
                    material={materials.Yellow}
                  />
                </group>
                <group
                  name="Cube081"
                  rotation={[-Math.PI, 0.004, -Math.PI]}
                  scale={100}
                >
                  <mesh
                    name="Cube081_Yellow_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube081_Yellow_0.geometry}
                    material={materials.Yellow}
                  />
                </group>
                <group name="Cube082" rotation={[0, -1.571, 0]} scale={100}>
                  <mesh
                    name="Cube082_Yellow_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube082_Yellow_0.geometry}
                    material={materials.Yellow}
                  />
                </group>
                <group
                  name="Cube083"
                  rotation={[Math.PI, -0.004, Math.PI]}
                  scale={100}
                >
                  <mesh
                    name="Cube083_Yellow_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube083_Yellow_0.geometry}
                    material={materials.Yellow}
                  />
                </group>
                <group
                  name="Cube084"
                  rotation={[-Math.PI, -0.004, -1.571]}
                  scale={100}
                >
                  <mesh
                    name="Cube084_Yellow_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube084_Yellow_0.geometry}
                    material={materials.Yellow}
                  />
                </group>
                <group
                  name="Cube085"
                  rotation={[Math.PI, -0.004, Math.PI]}
                  scale={100}
                >
                  <mesh
                    name="Cube085_Yellow_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube085_Yellow_0.geometry}
                    material={materials.Yellow}
                  />
                </group>
                <group
                  name="Cube086"
                  rotation={[Math.PI, -0.004, Math.PI]}
                  scale={100}
                >
                  <mesh
                    name="Cube086_Yellow_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube086_Yellow_0.geometry}
                    material={materials.Yellow}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
        <mesh
          name="Cube"
          castShadow
          receiveShadow
          geometry={nodes.Cube.geometry}
          material={materials.Material}
          position={[2.919, 2.772, 1.511]}
          scale={-0.021}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/untitled.glb");